version: '3.8'

services:
  trading_simulator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: always
